service: folk-webapp

custom:
  stage: ${opt:stage, self:provider.stage}
  bucketName: ${self:custom.stage}-folk-static-web
  distApiDomainId: ${self:custom.stage}-folk-api-web-dist
  domainName: ${self:custom.bucketName}.s3.amazonaws.com
  domainId: custom/${self:custom.domainName}
  service: ${self:custom.stage}-${self:service}
  cloudFrontOrigin:
    DomainName: ${self:custom.domainName}
    Id: ${self:custom.domainId}
    CustomOriginConfig:
      HTTPPort: 80
      HTTPSPort: 443
      OriginProtocolPolicy: https-only
  apiEnv:
    API_URL: ${ssm:/${self:custom.stage}/folk-webapp/DATAPLATTFORM_API_URL}
  authEnv:
    OAUTH_URL: ${ssm:/${self:custom.stage}/folk-webapp/DATAPLATTFORM_AUTH_URL}
    CLIENT_ID: ${ssm:/${self:custom.stage}/folk-webapp/CLIENT_ID~true}
    CLIENT_SECRET: ${ssm:/${self:custom.stage}/folk-webapp/CLIENT_SECRET~true}

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: nodejs12.x
  stackName: ${self:custom.service}
  timeout: 25
  httpApi:
    name: ${self:custom.service}-api
    payload: '2.0'
    cors: true

package:
  include:
    - backend/**
  exclude:
    - '*/**'
  individually: true

functions:
  edgeAdaptiveContent:
    handler: backend/edge.adaptiveContent
    name: ${self:custom.stage}-${self:service}-edge-adaptive-content-select
    events:
      - cloudFront:
          eventType: origin-request
          origin: ${self:custom.cloudFrontOrigin}

  authLogin:
    handler: backend/auth.login
    name: ${self:custom.service}-auth-login
    environment: ${self:custom.authEnv}
    role: LambdaRole
    events:
      - httpApi:
          method: GET
          path: /auth/login

  authCallback:
    handler: backend/auth.callback
    name: ${self:custom.service}-auth-callback
    environment: ${self:custom.authEnv}
    role: LambdaRole
    events:
      - httpApi:
          method: GET
          path: /auth/callback

  authUserInfo:
    handler: backend/auth.userInfo
    name: ${self:custom.service}-auth-userInfo
    environment: ${self:custom.authEnv}
    role: LambdaRole
    events:
      - httpApi:
          method: GET
          path: /auth/userInfo

  apiData:
    handler: backend/api.data
    name: ${self:custom.service}-api-data
    environment: ${self:custom.apiEnv}
    role: LambdaRole
    events:
      - httpApi:
          method: GET
          path: /api/data/{name}

  apiPages:
    handler: backend/api.pages
    name: ${self:custom.service}-api-pages
    environment: ${self:custom.apiEnv}
    role: LambdaRole
    events:
      - httpApi:
          method: GET
          path: /api/pages

  apiPageData:
    handler: backend/api.pageData
    name: ${self:custom.service}-api-page-data
    environment: ${self:custom.apiEnv}
    role: LambdaRole
    events:
      - httpApi:
          method: GET
          path: /api/pages/{page}

resources:
  Resources:
    LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.service}-lambda-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        Policies:
          - PolicyName: ${self:custom.stage}-ParameterStore-${self:service}
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - ssm:GetParameter
                    - ssm:GetParameters
                  Resource: #!Sub 'arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/${self:custom.stage}/${self:service}/*'
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:ssm'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'parameter/${self:custom.stage}/${self:service}/*'
                - Effect: Allow
                  Action:
                    - ssm:GetParameter
                    - ssm:GetParameters
                  Resource: # !Sub 'arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/${self:service}/*'
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:ssm'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'parameter/${self:service}/*'

    FolkStaticS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    FolkStaticS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: FolkStaticS3Bucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.bucketName}/*

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - ${self:custom.stage}.folk.knowit.no
          Origins:
            - ${self:custom.cloudFrontOrigin}
            - DomainName: g4usaty3db.execute-api.us-east-1.amazonaws.com # TODO: ref
              Id: ${self:custom.distApiDomainId}
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
                OriginSSLProtocols:
                  - TLSv1.2
          CacheBehaviors:
            - TargetOriginId: ${self:custom.distApiDomainId}
              ForwardedValues:
                Cookies:
                  Forward: all
                QueryString: true
                Headers:
                  - Accept
                  - Content-Type
                  - Authorization
                  - Origin
                  - Referer
              PathPattern: /auth/*
              ViewerProtocolPolicy: redirect-to-https
              AllowedMethods:
                - GET
                - HEAD
                - OPTIONS
                - PUT
                - PATCH
                - POST
                - DELETE
            - TargetOriginId: ${self:custom.distApiDomainId}
              ForwardedValues:
                QueryString: true
                Headers:
                  - Accept
                  - Content-Type
                  - Authorization
              PathPattern: /api/*
              ViewerProtocolPolicy: redirect-to-https
              AllowedMethods:
                - GET
                - HEAD
                - OPTIONS
                - PUT
                - PATCH
                - POST
                - DELETE
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            ViewerProtocolPolicy: redirect-to-https
          PriceClass: PriceClass_100
          ViewerCertificate:
            AcmCertificateArn:
              Fn::Join: 
                - ':'
                - - 'arn:aws:acm:us-east-1'
                  - !Ref 'AWS::AccountId'
                  - certificate/8c11e6a7-f8a2-4b06-a08d-890509e11473
            MinimumProtocolVersion: TLSv1.2_2019
            SslSupportMethod: sni-only

  Outputs:
    FolkStaticBucketOutput:
      Value:
        'Ref': FolkStaticS3Bucket
    CloudFrontDistributionOutput:
      Value:
        'Fn::GetAtt': [CloudFrontDistribution, DomainName]
