export const gruppeledere = [
  { id: 'abr@knowit.no' },
  { id: 'anders.pasche@knowit.no' },
  { id: 'anders.steen@knowit.no' },
  { id: 'christian.karlsson@knowit.no' },
  { id: 'christian.nyvoll@knowit.no' },
  { id: 'erik.lund@knowit.no' },
  { id: 'geinoh@knowit.no' },
  { id: 'hedda.dolva@knowit.no' },
  { id: 'hed@knowit.no' },
  { id: 'henning.lund-hanssen@knowit.no' },
  { id: 'hrj@knowit.no' },
  { id: 'joakim.lindgren@knowit.no' },
  { id: 'kak@knowit.no' },
  { id: 'klaus.stafto@knowit.no' },
  { id: 'lin@knowit.no' },
  { id: 'siv.brodsjomoen@knowit.no' },
  { id: 'sverre.bjorke@knowit.no' },
  { id: 'tormod.flesjo@knowit.no' },
  { id: 'zixuan.liu@knowit.no' },
]
