#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

GREEN='\033[0;32m'
PURPLE='\033[0;35m'
RED='\033[0;31m'
RESET='\033[0m' # No Color

echo \"${GREEN}[Husky] pre-commit checks:${RESET}\"

echo \”${PURPLE}Prettier Format Check${RESET}\"
yarn run format:check

echo \”${PURPLE}ESLint Check${RESET}\"
yarn run lint