#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

GREEN='\033[0;32m'
PURPLE='\033[0;35m'
RESET='\033[0m' # No Color

echo \"${GREEN}[Husky] FRONTEND:${RESET}\"

echo \”\> ${PURPLE}ESLint Check${RESET} \<\"
yarn run lint

echo \”\> ${PURPLE}Prettier Format Check${RESET} \<\"
yarn run format:check

echo \"${GREEN}[Husky] BACKEND:${RESET}\"
cd backend

echo \”\> ${PURPLE}ESLint Check${RESET} \<\"
yarn run lint

echo \”\> ${PURPLE}Prettier Format Check${RESET} \<\"
yarn run format:check

echo -e \"${GREEN}[Husky] all checks passed!${RESET}\"