
name: Knowit Folk Deploy Dev

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Configure AWS/Serverless
        uses: Teakowa/setup-serverless@main
        with:
          serverless_version: 1.66.0
          provider: aws
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test --ci --all 
      - name: Check build
        run: yarn build
      - name: Deploy backend
        run: yarn deploy:backend --stage dev
      - name: Deploy frontend
        run: yarn deploy:upload:dev
  