name: Deploy - Dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REACT_APP_ENV: development

jobs:
  deploy_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install serverless
        run: npm install -g serverless@3.25.1

      - name: Install server dependencies
        run: yarn workspaces focus server

      - uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy server
        run: serverless deploy --stage dev

  deploy_web:
    runs-on: ubuntu-latest
    needs: deploy_server
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Add env variable to .env file
        working-directory: ./apps/web
        run: echo "REACT_APP_ENV=$REACT_APP_ENV" >> .env

      - name: Install dependencies
        working-directory: apps/web
        run: yarn install

      - uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build web
        working-directory: apps/web
        run: yarn predeploy:dev

      - name: Deploy web
        working-directory: apps/web
        run: yarn deploy:dev

      - name: Update invalidation
        working-directory: apps/web
        run: yarn postdeploy:dev
