name: Deploy - Dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Install server dependencies
        working-directory: apps/server
        run: yarn workspaces focus server
      - uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: serverless deploy
        uses: serverless/github-action@v3
        with:
          args: serverless deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

  deploy_web:
    runs-on: ubuntu-latest
    needs: deploy_server
    steps:
      - uses: actions/checkout@v2
      - name: Set up node 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Install dependencies
        working-directory: apps/web
        run: yarn workspaces focus web
      - uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build web
        working-directory: apps/web
        run: yarn predeploy:dev
      - name: Deploy web
        working-directory: apps/web
        run: yarn deploy:dev
