
name: Knowit Folk - Deploy - Dev

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test --ci --all 
  deploy_backend:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up node 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Install serverless
        run: yarn install serverless@1.66.0
      - name: Install backend dependencies
        working-directory: backend
        run: yarn install
      - uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy backend
        run: yarn sls deploy --stage dev
  deploy_frontend:
    runs-on: ubuntu-latest
    needs: deploy_backend
    steps:
      - uses: actions/checkout@v2
      - name: Set up node 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Install dependencies
        run: yarn install
      - uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy frontend
        run: yarn deploy:dev
  