name: Knowit Folk - Frontend

defaults:
  run:
    working-directory: .

on:
  pull_request:
    paths-ignore:
      - 'backend/**'

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up node 14
  #       uses: actions/setup-node@v2-beta
  #       with:
  #         node-version: '14'

  #     - name: Install dependencies
  #       run: yarn install

  #     - name: Run tests
  #       run: yarn test --ci --all

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Check lints
        run: yarn lint

      - name: Check Format
        run: yarn format:check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
