name: Web

on:
  pull_request:
    paths:
      - "apps/web/**"

defaults:
  run:
    working-directory: "apps/web"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install

      - name: Check lints
        run: yarn lint

      - name: Check Format
        run: yarn format:check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
